### ISSUE TITLE
UE4 demo 编译不通过

### ISSUE THREAD

**Issue by hqztc** [xxxzhou/oeip#1]
点编译找不到一些.h文件 ，第三方库 貌似还少了oeip.dll和oeip-live.dll

**Comment by xxxzhou** [comment]
1 编译OEIP后，这个目录会保存OEIP生成给别的项目使用的文件。
![无标题2](https://user-images.githubusercontent.com/10152675/75752625-12b22900-5d64-11ea-8a66-678a7bfad2d6.png)
2 在OeipUE4\Plugins\OeipPlugins\ThirdParty\Oeip这个目录下，复制上面相应的目录到此。
![无标题](https://user-images.githubusercontent.com/10152675/75752390-961f4a80-5d63-11ea-8088-10f39ef732fa.png)
