### ISSUE TITLE
untiy3d和unreal报错

### ISSUE THREAD

**Issue by hpm21** [xxxzhou/oeip#3]
unity3d，运行testcamera，有usb摄像头。报错信息如下：
NullReferenceException: Object reference not set to an instance of an object
OeipWrapper.FixPipe.OeipVideoPipe..ctor (OeipWrapper.OeipPipe pipe) (at D:/git/oeip/OeipWrapper/FixPipe/OeipVideoPipe.cs:55)
CameraView.Awake () (at Assets/Oeip/Script/Tool/CameraView.cs:24)

**Comment by hpm21** [comment]
unity3d，运行testcamera，有usb摄像头。报错信息如下：
NullReferenceException: Object reference not set to an instance of an object
OeipWrapper.FixPipe.OeipVideoPipe..ctor (OeipWrapper.OeipPipe pipe) (at D:/git/oeip/OeipWrapper/FixPipe/OeipVideoPipe.cs:55)
CameraView.Awake () (at Assets/Oeip/Script/Tool/CameraView.cs:24)

**Comment by xxxzhou** [comment]
https://www.cnblogs.com/zhouxin/p/12568967.html
相应错误可以参考评论里的回复。
